#docker compose takes care of creating a common network!
#docker-compose -f <filename> up -> start the containers
#docker-compose -f <filename> down -> stop the containers
version: '3' 
services:
  mongodb: #container name
    image: mongo
    ports: 
    - 27017:27017 #host:container
    environment:
    - MONGO_INITDB_ROOT_USERNAME=mongoadmin 
    - MONGO_INITDB_ROOT_PASSWORD=secret 
    volumes:
    - db-data:/data/db #named volumes - name:<path to data in container>
  mongo-express:
    image: mongo-express
    depends_on: #need this else mongo-express starts before mongodb and can't connect
    - mongodb
    ports:
    - 8080:8081
    environment:
    - ME_CONFIG_MONGODB_ADMINUSERNAME=mongoadmin
    - ME_CONFIG_MONGODB_ADMINPASSWORD=secret 
    - ME_CONFIG_MONGODB_SERVER=mongodb

volumes: #list all volumes mounted in containers
  db-data:
    driver: local #create 
